add gis.md documentation
nf-core/configs pull request #352
Opened 2022-03-16 12:42 UTC by ajodeh-juma

---
name: New Config
about: A new cluster config
---

Please follow these steps before submitting your PR:

* [ ] If your PR is a work in progress, include `[WIP]` in its title
* [ ] Your PR targets the `master` branch
* [ ] You've included links to relevant issues, if any

Steps for adding a new config profile:
* [ ] Add your custom config file to the `conf/` directory
* [ ] Add your documentation file to the `docs/` directory
* [ ] Add your custom profile to the `nfcore_custom.config` file in the top-level directory
* [ ] Add your custom profile to the `README.md` file in the top-level directory
* [ ] Add your profile name to the `profile:` scope in `.github/workflows/main.yml`

2022-03-18 10:43 UTC, ggabernet approved these changes
Looks great!

2022-06-07 09:59 UTC, maxulysse commented
@nf-core-bot fix linting

2022-09-23 15:13 UTC, apeltzer requested changes

2022-09-23 15:13 UTC, apeltzer commented on docs/gis.md
> +# Run a nextflow pipeline with dependencies bundles in a conda environment
```suggestion
# Run a nextflow pipeline with dependencies bundled in a conda environment
```

2022-10-19 08:39 UTC, apeltzer approved these changes

2022-10-19 08:41 UTC, apeltzer commented
Going to ignore that one error here on the Nextflow installation for utd_sysbio as GHA seem to have quite some hiccups and it passed in the previous 2 CI Runs perfectly fine.

2022-10-19 08:41 UTC, merged