Added uw_hyak_pedslabs config
nf-core/configs pull request #486
Opened 2023-04-07 16:18 UTC by CarsonJM

---
name: New Config
about: A new cluster config
---

Please follow these steps before submitting your PR:

- [ ] If your PR is a work in progress, include `[WIP]` in its title
- [ ] Your PR targets the `master` branch
- [ ] You've included links to relevant issues, if any

Steps for adding a new config profile:

- [ ] Add your custom config file to the `conf/` directory
- [ ] Add your documentation file to the `docs/` directory
- [ ] Add your custom profile to the `nfcore_custom.config` file in the top-level directory
- [ ] Add your custom profile to the `README.md` file in the top-level directory
- [ ] Add your profile name to the `profile:` scope in `.github/workflows/main.yml`

2023-07-03 08:45 UTC, jfy133 requested changes
Sorry for the long delay! Apparently all our notifications for this repo stopped...

Overall LGTM but please check the `docs.md` of other configs to make sure you keep roughly to the same structure (we will likely have better (read: actual) docs rendering on the nf-core website soon, so we want to have a certain level of standardisation) [also see prettier error]

2023-07-03 09:03 UTC, maxulysse commented
@nf-core-bot fix linting pretty please :pray:

2023-07-05 14:40 UTC, CarsonJM commented
@nf-core-bot fix linting

2023-07-06 07:33 UTC, maxulysse approved these changes

2023-07-08 07:19 UTC, jfy133 approved these changes

2023-07-08 07:23 UTC, merged