[WIP] Add `tuebingen_apg` profile
nf-core/configs pull request #487
Opened 2023-04-16 09:20 UTC by TCLamnidis

---
name: New Config
about: A new cluster config
---

Please follow these steps before submitting your PR:

- [x] If your PR is a work in progress, include `[WIP]` in its title
- [x] Your PR targets the `master` branch
- [x] You've included links to relevant issues, if any

Steps for adding a new config profile:

- [ ] Add your custom config file to the `conf/` directory
- [ ] Add your documentation file to the `docs/` directory
- [ ] Add your custom profile to the `nfcore_custom.config` file in the top-level directory
- [ ] Add your custom profile to the `README.md` file in the top-level directory
- [ ] Add your profile name to the `profile:` scope in `.github/workflows/main.yml`

2023-04-26 11:35 UTC, jfy133 requested changes
Mostly docs stuff but otherwise loks good

2023-04-26 11:35 UTC, jfy133 commented on README.md
> +- [University of Tuebingen, APG Group](docs/tubingen_apg.md)
```suggestion
- [TUBINGEN_APG](docs/tubingen_apg.md)
```

2023-04-26 11:35 UTC, jfy133 commented on docs/tubingen_apg.md
> +- `/opt/resources`
```suggestion
Using this profile, a docker image containing all of the required software will be downloaded, and converted to a singularity container before execution of the pipeline. The image will be stored in the cache directory:

```
/opt/container_tmp/apptainer/nextflow
```
```

2023-04-26 15:33 UTC, TCLamnidis commented on docs/tubingen_apg.md
> +- `/opt/resources`
```suggestion
Using this profile, a docker image containing all of the required software will be downloaded, and converted to a singularity container before execution of the pipeline. The image will be stored in the cache directory:
`/opt/container_tmp/apptainer/nextflow`
```

2023-04-27 12:23 UTC, scarlhoff commented on docs/tubingen_apg.md
> +> NB: Nextflow will need to submit the jobs via SLURM to the clusters and as such the commands above will have to be executed on one of the head nodes. If in doubt contact IT.
```suggestion
> NB: The commands to run a pipeline will have to be executed on one of the head nodes, so Nextflow can submit the jobs to the clusters via SLURM. If in doubt, contact IT.
```

2023-04-27 14:43 UTC, jfy133 approved these changes

2023-04-27 14:44 UTC, jfy133 commented
I agree with @scarlhoff it _should_ be Tuebingen, but technically and documentally everything is OK to me now.

2023-04-27 14:54 UTC, scarlhoff approved these changes

2023-04-27 15:37 UTC, merged