Adding seattle childrens config
nf-core/configs pull request #654
Opened 2024-03-19 21:17 UTC by ybaeus

---
name: New Config
about: A new cluster config
---

Please follow these steps before submitting your PR:

- [ ] If your PR is a work in progress, include `[WIP]` in its title
- [ ] Your PR targets the `master` branch
- [ ] You've included links to relevant issues, if any

Steps for adding a new config profile:

- [ ] Add your custom config file to the `conf/` directory
- [ ] Add your documentation file to the `docs/` directory
- [ ] Add your custom profile to the `nfcore_custom.config` file in the top-level directory
- [ ] Add your custom profile to the `README.md` file in the top-level directory
- [ ] Add your profile name to the `profile:` scope in `.github/workflows/main.yml`

2024-03-19 22:35 UTC, CarsonJM requested changes

2024-03-19 22:35 UTC, CarsonJM commented on README.md
> +- [SEATTLECHILRENS](docs/seattlechildrens.md)
```suggestion
- [SEATTLECHILDRENS](docs/seattlechildrens.md)
```

2024-03-19 22:35 UTC, CarsonJM commented on conf/seattlechildrens.config
> +    project                     = ""      // please put your own project code
The config file is not editable by the user, so maybe include a param here

```suggestion
    project                     = "${params.project}" 
```

2024-03-19 22:47 UTC, CarsonJM commented
@nf-core-bot fix linting

2024-03-20 10:15 UTC, jfy133 commented
@CarsonJM @ybaeus if you merge from master, there should be nf-core bot working again (I hope )

2024-03-20 10:46 UTC, mashehu commented
@nf-core-bot fix linting

2024-03-20 15:05 UTC, jfy133 commented
@mashehu doesn't seem to be working :cry:

2024-03-20 16:45 UTC, ybaeus reviewed
Finishing the review

2024-03-20 18:21 UTC, jennylsmith requested changes
It looks great! I just realized that neerja's edits were not merged into `main`. There was some info about the HPC `project info` command line tool. Could you do a pull request for the branch `commits_nk` on our repo?

2024-03-20 19:16 UTC, ybaeus commented on conf/seattlechildrens.config
> +    project                     = "${params.project}"
```suggestion
    project                     = "${params.project}"
```

2024-03-20 19:23 UTC, ybaeus commented on conf/seattlechildrens.config
> +    project                     = "${params.project}"
remove trailing whitespace

2024-03-20 20:17 UTC, mashehu commented
> @mashehu doesn't seem to be working 😢

It does work, the problem is just that editorconfig errors are not autofixed, so somebody needs to manually fix them (unfortunately I can't push to the remote)

2024-03-20 20:24 UTC, ybaeus commented on docs/seattlechildrens.md
> +   Make sure that channel priority is set to flexible using the following comments:
```suggestion
Make sure that channel priority is set to flexible using the following comments:
```

2024-03-20 20:25 UTC, ybaeus reviewed
Could anyone please check line 32 of ./docs/seattlechildrens.md?

2024-03-20 20:30 UTC, mashehu commented
@nf-core-bot fix linting

2024-03-20 20:33 UTC, mashehu commented on docs/seattlechildrens.md
> +Make sure that channel priority is set to flexible using the following comments:
```suggestion

Make sure that channel priority is set to flexible using the following comments:
```

2024-03-20 20:33 UTC, mashehu commented on docs/seattlechildrens.md
> +Make sure that channel priority is set to flexible using the following comments:
this should finally fix the linting

2024-03-20 21:44 UTC, jennylsmith approved these changes
Looks awesome, thank you!

2024-03-20 21:54 UTC, merged